import useSWR from "swr";

import { POPULAR_BAES_URL } from "../configs/config";

import Head from "next/head";
import Grid from "../components/Grid";
import Layout from "../components/Layout";
import { Movies } from "../types/movie";

export default function Home() {
  const fetcher = (url: string): Promise<Movies> =>
    fetch(url).then((res) => res.json());

  const endpoint = `${POPULAR_BAES_URL}`;

  const { data, error } = useSWR(endpoint, fetcher);
  console.log({ data, error });

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data && (
        <Grid
          page={data?.page}
          results={data?.results}
          total_pages={data?.total_pages}
          total_results={data?.total_results}
        ></Grid>
      )}
    </Layout>
  );
}
