import Head from "next/head";
import Link from "next/link";
import useSWR from "swr";
import { useState } from "react";

import Card from "../components/Card";
import Grid from "../components/Grid";
import Layout from "../components/Layout";
import LoadMore from "../components/LoadMore";

import { POPULAR_BAES_URL } from "../configs/config";
import { Movies } from "../types/movie";

const fetcher = async (url: string) => await (await fetch(url)).json();

export default function Home() {
  const [page, setPage] = useState(1);
  const endpoint = `${POPULAR_BAES_URL}&page=${page}`;

  const { data: movies, error } = useSWR<Movies>(endpoint, fetcher);
  // console.log({ data, error });

  return (
    <Layout>
      <Head>
        <title>Next JS Movie DB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {movies && (
        <Grid header="Popular Movies">
          {movies?.results.map((movie, movieIndex) => (
            <Link href={movie?.id.toString()} key={movieIndex}>
              <a>
                <Card movie={movie} />
              </a>
            </Link>
          ))}
        </Grid>
      )}

      <LoadMore setPage={setPage} />
    </Layout>
  );
}
